spring:
  application:
    name: barointern9
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/var/lib/barointern9
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always


jwt:
  secret-key: ${JWT_SECRET_KEY}
